# See https://www.home-assistant.io/components/sensor.thethingsnetwork/
- platform: thethingsnetwork
  device_id: my-seeeduino
  values:
    humi: "%"
    temp: "°C"
    value1: ""
    value2: ""
    value3: ""

# Measured values range from about 0 to 1023 (in theory).
# In a first test I measured a range from 150 - 200 (water)
# to 1023 (dry).
#
# Scale is not linear, first temporary results:
# - very wet soil   200
# - wet soil        300 - 400
# - quite good soil 500 - 600 
# - too dry soil    > 700
#
# Current calucalation of percentage value is just a temporary assumption.
- platform: template
  sensors:
    ttnplant1: 
      friendly_name: "Zick-Zack Strauch"
      unit_of_measurement: "%"
      value_template: "{{ 100 - (100/923*(states('sensor.myseeeduino_value1') | int - 100)) | int }}"
    ttnplant2: 
      friendly_name: "Thymian"
      unit_of_measurement: "%"
      value_template: "{{ 100 - (100/923*(states('sensor.myseeeduino_value2') | int - 100)) | int }}"
    ttnplant3: 
      friendly_name: "Thymian Marco"
      unit_of_measurement: "%"
      value_template: "{{ 100 - (100/923*(states('sensor.myseeeduino_value3') | int - 100)) | int }}"
